services:
  _defaults:
    autowire: true
    autoconfigure: true

  Snoke\InterfaceAssociations\:
    autowire: true
    autoconfigure: true
    resource: '../../'

  Snoke\InterfaceAssociations\EventListener\LoadClassMetadataListener: