snoke_interface_associations:
  remap:
#    - source: 'Snoke\OAuthServer\Interface\AuthenticatableInterface'
#      target: 'App\Entity\User'
#      class: 'Snoke\OAuthServer\Entity\AccessToken'
#      field: 'user'